name: PR-Test

on:
   pull_request:
      paths-ignore:
         - '*.md'
         - '*.yml'

jobs:
   test_linux:
      if: ${{ github.repository == 'kotest/kotest-property-datetime' }}
      strategy:
         matrix:
            target:
               - jvmTest
               - jsTest
               - wasmJsTest
               - linuxX64Test linuxArm64TestKlibrary
      uses: ./.github/workflows/run-gradle.yml
      with:
         runs-on: ubuntu-latest
         ref: ${{ inputs.ref }}
         task: ${{ matrix.target }}

   test_mac:
      if: ${{ github.repository == 'kotest/kotest-property-datetime' }}
      strategy:
         fail-fast: true
         matrix:
            target:
               - macosX64Test macosArm64Test
               - iosX64Test iosSimulatorArm64Test iosArm64TestKlibrary
               - tvosX64Test tvosArm64TestKlibrary tvosSimulatorArm64Test
               - watchosArm32TestKlibrary watchosArm64TestKlibrary watchosX64Test watchosSimulatorArm64Test watchosDeviceArm64TestKlibrary
      uses: ./.github/workflows/run-gradle.yml
      with:
         runs-on: macos-latest
         ref: ${{ inputs.ref }}
         task: ${{ matrix.target }}

   test_windows:
      if: ${{ github.repository == 'kotest/kotest-property-datetime' }}
      uses: ./.github/workflows/run-gradle.yml
      with:
         runs-on: windows-latest
         ref: ${{ inputs.ref }}
         task: mingwX64Test
